language: swift
osx_image: xcode14
xcode_project: Triangle App.xcodeproj # path to your xcodeproj folder done
xcode_scheme: Triangle App
xcode_destination: platform=iOS Simulator,OS=16.0,name=iPhone 14 Plus
